api:
  address: "localhost:8000"
mongo:
  host: localhost
  port: 27017
  db: crawunit
  username: ""
  password: ""
  authSource: "admin"
redis:
  address: localhost
  password: ""
  database: 1
  port: 6379
log:
  level: info
  path: "/var/logs/crawunit"
  isDeletePeriodically: "N"
  deleteFrequency: "@hourly"
spider:
  path: "/app/spiders"
task:
  workers: 4
other:
  tmppath: "/tmp"