api:
  address: "localhost:8000"
mongo:
  host: localhost
  port: 27017
  db: crawlab_test
  username: ""
  password: ""
  authSource: "admin"
redis:
  address: localhost
  password: ""
  database: 1
  port: 6379
log:
  level: info
  path: "/var/logs/crawunit"
  isDeletePeriodically: "N"
  deleteFrequency: "@hourly"
server:
  host: 0.0.0.0
  port: 8000
  master: "Y"
  secret: "crawunit"
  register:
    type: "mac"
    ip: ""
  lang:
    python: "Y"
    node: "N"
    java: "N"
    dotnet: "N"
    php: "N"
spider:
  path: "/app/spiders"
task:
  workers: 4
other:
  tmppath: "/tmp"
setting:
  allowRegister: "N"
  enableTutorial: "N"
  runOnMaster: "Y"
  demoSpiders: "N"
  checkScrapy: "Y"
  autoInstall: "Y"
