version: '3.3'
services:
  master: 
    image: crawunit:v2.0.0
    container_name: master
    environment:
      CRAWLAB_SERVER_MASTER: "Y" 
      CRAWLAB_MONGO_HOST: "47.93.195.128"  
      CRAWLAB_MONGO_PORT: "27017"  
      CRAWLAB_REDIS_ADDRESS: "47.93.195.128"  
      CRAWLAB_REDIS_PORT: "6379"  
    ports:    
      - "8080:8080" 
      
  worker1: 
    image: crawunit:v2.0.0
    container_name: worker1
    environment:
      CRAWLAB_SERVER_MASTER: "N"  
      CRAWLAB_MONGO_HOST: "47.93.195.128"  
      CRAWLAB_MONGO_PORT: "27017"  
      CRAWLAB_REDIS_ADDRESS: "47.93.195.128"  
      CRAWLAB_REDIS_PORT: "6379"  
      
            
  worker2: 
    image: crawunit:v2.0.0
    container_name: worker2
    environment:
      CRAWLAB_SERVER_MASTER: "N"  
      CRAWLAB_MONGO_HOST: "47.93.195.128"  
      CRAWLAB_MONGO_PORT: "27017"  
      CRAWLAB_REDIS_ADDRESS: "47.93.195.128"  
      CRAWLAB_REDIS_PORT: "6379"  

